---
- name: Web server
  hosts: linux1
  become: true

  vars:
    - website_name: Test de Ansible-AWX
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Crear página web personalizada
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Asegurar que Nginx está corriendo
      service:
        name: nginx
        state: started
        enabled: yes